identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: false
  ignores_interpolated_strings: true
  ignores_urls: true
